name: Preview deploy to Vercel

on:
  push:
    branches-ignore:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        id: install-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Vercel
        id: install-vercel
        run: npm install -g vercel@latest

      - name: Pull Vercel config
        id: pull-vercel-config
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build app
        id: build-app
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy app
        id: deploy-app
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
